import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const helvetica = localFont({
    src: [
        {
            path: "../../public/fonts/helvetica/Helvetica.ttf",
        },
        {
            path: "../../public/fonts/helvetica/Helvetica-Bold.ttf",
        },
        {
            path: "../../public/fonts/helvetica/Helvetica-BoldOblique.ttf",
        },
        {
            path: "../../public/fonts/helvetica/Helvetica-Light.ttf",
        },
        {
            path: "../../public/fonts/helvetica/Helvetica-Oblique.ttf",
        },
    ],
    display: 'swap',
    style: 'normal',
    variable: '--font-helvetica'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helvetica.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
